/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'selemis' at '10/15/16 1:55 AM' with Gradle 2.13
 *
 * @author selemis, @date 10/15/16 1:55 AM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
