/*
 * This Spock specification was auto generated by running the Gradle 'init' task
 * by 'selemis' at '10/15/16 1:55 AM' with Gradle 2.13
 *
 * @author selemis, @date 10/15/16 1:55 AM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
